[project]
name = "advent-of-code"
version = "0.1.0"
description = "Apreche’s Advent of Code solutions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bitarray>=3.0.0",
    "tqdm>=4.67.0",
]
